Add files via upload
Junior-Coders-Devs/AI-Challenge pull request #16
Opened 2022-11-16 20:15 UTC by Ciornache

Implemented knight

2022-11-16 22:44 UTC, RDaniel99 commented on Chess/knight.h
> +    struct MoveBy
Buna ideea!

2022-11-16 22:52 UTC, RDaniel99 requested changes
Foarte interesanta ideea de la makeMove 👏 Mici modificari de facut, dar una peste alta, foarte fain codul, well done!

2022-11-16 22:52 UTC, RDaniel99 commented on Chess/knight.h
> +    vector<MoveBy> getMoves();
E necesar sa fie public?

2022-11-16 22:52 UTC, RDaniel99 commented on Chess/knight.cpp
> +    vector <MoveBy> moves = getMoves();
Ai deja acces la moves prin this->moves

2022-11-16 22:52 UTC, RDaniel99 commented on Chess/knight.cpp
> +        ok |= (i == currentMove && this->isValidMove(diffRow, diffColumn));
1.
`this->isValidMove(diffRow, diffColumn);`

Nu depinde de i, poate fi facuta o singura data la inceput

2. Pare ca asta e mai mult o validare care verifica daca mutarea e legala (regulamentara).
Poti sa o scoti intr-o functie separata de `isLegalMove(diffRow, diffColumn)` care sa intoarca true sau false daca este in acel vector de `moves`. Vezi exemplu la clasa `Bishop`

2022-11-16 22:52 UTC, RDaniel99 commented on Chess/knight.cpp
> +vector <Knight::MoveBy>  Knight::getMoves() {
Nu cred ca e necesar

2022-11-16 22:52 UTC, RDaniel99 commented on Chess/knight.h
> +#include <bits/stdc++.h>
https://www.quora.com/Is-it-good-practice-to-use-include-bits-stdc++-h-in-programming-contests-instead-of-listing-a-lot-of-includes

2022-11-16 22:52 UTC, RDaniel99 commented on Chess/knight.h
> +#include "piece.h"
O linie libera inainte de include-uri

2022-11-16 22:52 UTC, RDaniel99 commented on Chess/knight.cpp
> +void Knight::makeMove(int diffRow, int diffColumn) {
Poti adauga acel @inheritDoc, vezi `bishop.cpp` ca exemplu

2022-11-17 16:21 UTC, Ciornache commented on Chess/knight.cpp
> +    vector <MoveBy> moves = getMoves();
a da ups :))

2022-11-17 19:33 UTC, RDaniel99 submitted a review, later dismissed
Good job 👏

2022-11-17 19:33 UTC, RDaniel99 commented on Chess/knight.cpp
> +*/
Mutata la makeMove

2022-11-22 12:32 UTC, RDaniel99 approved these changes

2022-11-23 17:52 UTC, merged