initializeBlackPieces + my take on initializeBoard
Junior-Coders-Devs/AI-Challenge pull request #32
Opened 2022-11-30 14:59 UTC by Ciornache

2022-12-02 15:30 UTC, RDaniel99 requested changes
Foarte foarte fain codul! Se vad imbunatatiri!!! Good job!! 👏 
Trecem la nivelul urmator de imbunatatiri: **enums** si delegari de responsabilitati in alte clase (le mai denumim "servicii")😉

2022-12-02 15:30 UTC, RDaniel99 commented on Chess/config.h
> +                                "BlackOnBlack/pawn.jpg"};
N-ar trebui si un king?

2022-12-02 15:30 UTC, RDaniel99 commented on Chess/painter.cpp
> +                drawSquare(i, j, 0, "Backgrounds/Black.jpg");
Extrage tot asa in doua variabile din config

2022-12-02 15:30 UTC, RDaniel99 commented on Chess/painter.cpp
> +    line(OFFSET_X + diffLin + SQUARE_SIZE, OFFSET_Y + diffCol,
Nu e inmultit cu SQUARE_SIZE?

2022-12-02 15:30 UTC, RDaniel99 commented on Chess/painter.cpp
> +    if(patrat == 0)
Sa pastram consistenta si sa punem totul in engleza
Totodata, am putea sa denumim altfel variabila asta ca sa fie cat mai clean posibil: sa punem in config un enum pentru culori (o sa ne trebuiasca si in alte contexte probabil) care sa aiba doua valori: BLACK si WHITE. Si aici sa pasezi un astfel de enum in loc de int, ca sa fie mai usor de citit, iar variabila sa se denumeasca color si if-ul ar fi ceva de genul:
```if(color == BLACK)```

2022-12-02 15:30 UTC, RDaniel99 commented on Chess/painter.cpp
> +                    loadPiece(i, j, BlackOnBlackPaths[i / 2 - 1]);
As extra loadPiece intr-o clasa separata denumita ```PiecePainter```

2022-12-02 15:30 UTC, RDaniel99 commented on Chess/painter.cpp
> +                    loadPiece(i, j, BlackOnBlackPaths[i / 2 - 1]);
Si sa se ocupe clasa respectiva cu determinatul tipului de piesa in functie de row/column

2022-12-02 15:30 UTC, RDaniel99 commented on Chess/painter.cpp
> +                    loadPiece(i, j, BlackOnBlackPaths[i / 2 - 1]);
Totodata, ar merge adaugat si un enum pentru piese :D

2022-12-02 15:30 UTC, RDaniel99 commented on Chess/painter.cpp
> +void Painter::loadPiece(int row, int column, char image[])
Probabil va face parte din ```PiecePainter```

2022-12-02 15:31 UTC, RDaniel99 commented
Vezi ca proiectul nu ruleaza 🤕

2022-12-02 18:25 UTC, Ciornache commented on Chess/config.h
> +                                "BlackOnBlack/pawn.jpg"};
da corect my bad

2022-12-02 18:26 UTC, Ciornache commented on Chess/painter.cpp
> +    line(OFFSET_X + diffLin + SQUARE_SIZE, OFFSET_Y + diffCol,
nu cred

2022-12-04 20:18 UTC, RDaniel99 approved these changes
GG

2022-12-04 20:19 UTC, merged